//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_CFG_PAGE1                   102
#define IDD_CFG_PAGE5                   105
#define IDD_ABOUT                       111
#define IDD_CFG_PAGE2                   112
#define IDB_YM2413                      113
#define IDD_CFG_PAGE3                   113
#define IDD_CFG_PAGE4                   114
#define IDD_PLSDLG                      119
#define IDD_MIXER                       121
#define IDD_EDIT2413                    122
#define IDD_SWITCH                      124
#define IDD_KSSDLG                      128
#define IDD_CFG_PAGE6                   129
#define IDI_NEXT                        143
#define IDI_STOP                        144
#define IDI_PLAY                        145
#define IDI_PREV                        146
#define IDI_MSXPLUG                     149
#define IDD_CFG_PAGE7                   159
#define IDD_PANPOT                      162
#define IDD_PANDLG                      163
#define IDB_ASCII                       164
#define IDD_CFG_PAGE8                   168
#define IDR_MENU1                       170
#define IDD_OPTDLG                      172
#define IDR_EXTRA                       174
#define IDD_MASKDLG                     175
#define IDM_MASK                        176
#define IDC_PSGVOL                      1007
#define IDC_MASTERVOL                   1008
#define IDC_SCCVOL                      1011
#define IDC_OPLLVOL                     1012
#define IDC_OPLVOL                      1013
#define IDC_ENABLE_MBM                  1015
#define IDC_PSGMUTE                     1015
#define IDC_ENABLE_MGS                  1016
#define IDC_SCCMUTE                     1016
#define IDC_ENABLE_MPK                  1018
#define IDC_OPLLMUTE                    1018
#define IDC_ENABLE_KSS                  1019
#define IDC_OPLMUTE                     1019
#define IDC_ENABLE_OPX                  1020
#define IDC_PLAYTIME                    1021
#define IDC_SET_MGSDRV                  1022
#define IDC_LOOPNUM                     1022
#define IDC_FADETIME                    1023
#define IDC_SET_KINROU                  1024
#define IDC_SWITCH_ON                   1024
#define IDC_SILENT                      1024
#define IDC_BUFFER                      1025
#define IDC_SWITCH_OFF                  1025
#define IDC_SET_MPK106                  1026
#define IDC_REVERSE                     1028
#define IDC_OPXDRV_PATH                 1029
#define IDC_SET_OPXDRV                  1030
#define IDC_SET_MPK103                  1031
#define IDC_FMBIOS_PATH                 1032
#define IDC_ENABLE_BGM                  1033
#define IDC_SET_FMBIOS                  1033
#define IDC_MGSDRV_PATH                 1034
#define IDC_KINROU_PATH                 1035
#define IDC_MPK106_PATH                 1036
#define IDC_MPK103_PATH                 1037
#define IDC_TITLE                       1043
#define IDC_FILENAME                    1044
#define IDC_LOOPTIME                    1046
#define IDC_SONG                        1048
#define IDC_LOOP                        1050
#define IDC_LOAD                        1091
#define IDC_MIXER_SPIN                  1092
#define IDC_SAVE                        1092
#define IDC_MIXER_VALUE                 1106
#define IDC_RADIO96K                    1107
#define IDC_RADIO48K                    1109
#define IDC_RADIO44K                    1110
#define IDC_RADIO32K                    1111
#define IDC_RADIO22K                    1112
#define IDC_RADIO11K                    1113
#define IDC_MIXER_SLIDER                1120
#define IDC_VOICETREE                   1129
#define IDC_RESET                       1131
#define IDC_SWITCH_TITLE                1132
#define IDC_MIXER_TITLE                 1133
#define IDC_PSGDB                       1135
#define IDC_SCCDB                       1136
#define IDC_OPLLDB                      1137
#define IDC_OPLDB                       1138
#define IDC_TONEINFO                    1138
#define IDC_MASTERDB                    1139
#define IDC_RESTORE                     1141
#define IDC_OVERWRITE                   1142
#define IDC_PSGSPIN                     1143
#define IDC_SCCSPIN                     1144
#define IDC_OPLLSPIN                    1145
#define IDC_OPLSPIN                     1146
#define IDC_PREV                        1147
#define IDC_NEXT                        1148
#define IDC_LOOPSPIN                    1151
#define IDC_SONGSPIN                    1152
#define IDC_SILENTSPIN                  1152
#define IDC_UPDATE                      1158
#define IDC_CLEAN                       1159
#define IDC_TDLEVEL0                    1166
#define IDC_TDLEVEL1                    1167
#define IDC_SYNC                        1168
#define IDC_TDMODE0                     1175
#define IDC_TDMODE1                     1176
#define IDC_TDMODE2                     1177
#define IDC_TDMODE3                     1178
#define IDC_PSGCHK                      1181
#define IDC_PLAYTIME_NOW                1182
#define IDC_SCCCHK                      1183
#define IDC_OPLLCHK                     1184
#define IDC_OPLCHK                      1185
#define IDC_PLAY                        1187
#define IDC_EXTRA                       1192
#define IDC_ID                          1193
#define IDC_TYPE                        1194
#define IDC_STOP                        1194
#define IDC_REFRESH                     1195
#define IDC_POS                         1197
#define IDC_SEARCH                      1198
#define IDC_LOGO                        1201
#define IDC_MULTI                       1203
#define IDC_PSG_HQ                      1212
#define IDC_SCC_HQ                      1213
#define IDC_AUTO_SAVE                   1213
#define IDC_OPLL_HQ                     1215
#define IDC_CLK_AUTO                    1216
#define IDC_CLK_SLOW                    1217
#define IDC_CLK_FAST                    1218
#define IDC_CLK_FASTER                  1219
#define IDC_CLK_FASTEST                 1220
#define IDC_PSG_CUTOFF                  1223
#define IDC_COPYRIGHT                   1224
#define IDC_SCC_CUTOFF                  1225
#define IDC_OPLL_CUTOFF                 1227
#define IDC_OPL_PAN                     1228
#define IDC_OPL_CUTOFF                  1229
#define IDC_OPLL_PAN                    1229
#define IDC_SCC_PAN                     1232
#define IDC_PSG_PAN                     1233
#define IDC_PANEDIT                     1239
#define IDC_SLIDER                      1241
#define IDC_R                           1244
#define IDC_C                           1245
#define IDC_ENABLE_DCF                  1248
#define IDC_ENABLE_RCF                  1253
#define IDC_SET_MBMDRV                  1253
#define IDC_MBMDRV_PATH                 1254
#define IDC_SYNC0                       1257
#define IDC_SYNC1                       1258
#define IDC_MBM_MODE0                   1264
#define IDC_MBM_MODE1                   1265
#define IDC_MBM_MODE2                   1266
#define IDC_MBKPATH                     1267
#define IDC_MBKBTN                      1268
#define IDC_MGSTEXT                     1269
#define IDC_MBKDUMMY                    1273
#define IDC_PSG1                        1275
#define IDC_PSG2                        1276
#define IDC_PSG3                        1277
#define IDC_SCC1                        1278
#define IDC_SCC2                        1279
#define IDC_SCC3                        1280
#define IDC_SCC4                        1281
#define IDC_SCC5                        1282
#define IDC_INIT                        1284
#define IDC_OPLL1                       1288
#define IDC_OPLL2                       1289
#define IDC_OPLL3                       1290
#define IDC_OPLL4                       1291
#define IDC_OPLL_STEREO                 1291
#define IDC_OPLL5                       1292
#define IDC_OPLL_2413                   1292
#define IDC_OPLL6                       1293
#define IDC_OPLL_VRC7                   1293
#define IDC_OPLL7                       1294
#define IDC_OPLL_281B                   1294
#define IDC_OPLL8                       1295
#define IDC_SILENT_ENABLE               1295
#define IDC_CHECK1                      1297
#define IDC_EXPAND_INFO                 1297
#define IDC_OPLL9                       1304
#define IDC_OPLL_BD                     1309
#define IDC_OPLL_HH                     1310
#define IDC_OPLL_SD                     1311
#define IDC_OPLL_TOM                    1312
#define IDC_OPLL_CYM                    1313
#define IDC_OPL1                        1315
#define IDC_OPL2                        1316
#define IDC_OPL3                        1317
#define IDC_OPL4                        1318
#define IDC_OPL5                        1319
#define IDC_OPL6                        1320
#define IDC_OPL7                        1321
#define IDC_OPL8                        1322
#define IDC_OPL9                        1323
#define IDC_OPL_BD                      1324
#define IDC_OPL_HH                      1325
#define IDC_OPL_SD                      1326
#define IDC_OPL_TOM                     1327
#define IDC_OPL_CYM                     1328
#define IDC_OPL_PCM                     1329
#define IDC_DA                          1330
#define IDC_OPLL_PCM                    1331
#define IDC_PSG_DISABLE                 2048
#define IDC_PSG_AUTO                    2049
#define IDC_PSG_AY                      2050
#define IDC_PSG_YM                      2051
#define IDC_SCC_DISABLE                 4096
#define IDC_SCC_AUTO                    4097
#define IDC_SCC_NORMAL                  4098
#define IDC_SCC_PLUS                    4099
#define IDC_STEREO_AUTO                 4100
#define IDC_STEREO_OFF                  4101
#define IDC_STEREO_ON                   4102
#define IDC_ENABLE_STEREO               4102
#define IDM_CONFIG                      40004
#define IDM_VEDIT                       40005
#define IDM_OPTDLG                      40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1298
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
